entryPoints:
  web:
    address: "0.0.0.0:80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: "0.0.0.0:443"

api:
  dashboard: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: jouinianis248@gmail.com
      storage: /acme.json
      httpChallenge:
        entryPoint: web

providers:
  docker:
    exposedByDefault: false
